version: "3"

services:

  # serverpy:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     FLASK_APP: "app.py"
  #   command: "flask run --host=0.0.0.0"
  #   networks: 
  #     - net_serverpy

  redis:
    image: 'redis:5.0.3-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    networks: 
      - net_serverpy

  celery:
    build: .
    command: "celery -A app.celery worker -l INFO"
    networks: 
      - net_serverpy
      - serverdb_net_serverdb
      - serverauth_net_servergo

  gunicorn:
    build: .
    command: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    ports:
      - "5000:5000"
    networks: 
      - net_serverpy
      - serverdb_net_serverdb
      - serverauth_net_servergo

volumes:
  redis:

networks:
  net_serverpy:

  serverdb_net_serverdb:
    external: true

  serverauth_net_servergo:
    external: true